export type BlockId = string;
/** Validated at runtime as BLK-YYYY-NNNN, e.g. BLK-2026-0001. */
export type BlockNumber = `BLK-${number}-${string}`;
export type DimensionUnit = "FT" | "M";
export type VolumeUnit = "CFT" | "M3";
export type GraniteGrade = "A" | "B" | "C";
export type GraniteMaterial = "Black Granite" | "Grey Granite" | "Tan Brown";
export type BlockStatus = "AVAILABLE" | "RESERVED" | "DISPATCHED" | "REJECTED";
export type InitialBlockStatus = Extract<BlockStatus, "AVAILABLE" | "REJECTED">;

export interface BlockDimensions {
  readonly length: number;
  readonly width: number;
  readonly height: number;
  readonly unit: DimensionUnit;
}

export interface Quarry {
  readonly id: string;
  readonly name: string;
}
export interface Pit {
  readonly id: string;
  readonly quarryId: string;
  readonly name: string;
}
export interface BlockCustomer {
  readonly id: string;
  readonly name: string;
}

export interface GraniteBlock {
  readonly id: BlockId;
  readonly blockNumber: BlockNumber;
  /** ISO calendar date YYYY-MM-DD, without timezone conversion. */
  readonly productionDate: string;
  readonly quarryId: string;
  readonly pitId: string;
  readonly material: GraniteMaterial;
  readonly grade: GraniteGrade;
  /** Original entry values/units, never overwritten by conversion. */
  readonly dimensions: BlockDimensions;
  /** Canonical, unrounded internal volume in cubic metres. */
  readonly volumeM3: number;
  readonly stockyardLocation: string;
  readonly status: BlockStatus;
  readonly supervisor: string;
  readonly remarks: string;
}

/** Volume is always calculated. Identity can be supplied or generated by the store. */
export type AddBlockInput = Omit<
  GraniteBlock,
  "id" | "blockNumber" | "volumeM3" | "status" | "remarks"
> & {
  readonly id?: string;
  readonly blockNumber?: string;
  readonly status?: InitialBlockStatus;
  readonly remarks?: string;
};
